version: '3'

services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=db
    ports:
      - 5430:5432
#    volumes:
#      - ./init/001_init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always